image: docker:20.10
services:
  - docker:20.10-dind

stages:
  - build

build-main:
  image: cfmanteiga/alpine-bash-curl-jq
  stage: build
  only:
    - main
  script:
    - chmod +x ./gitrise.sh
    - ./gitrise.sh -a $BITRISE_ACCESS_TOKEN -s $BITRISE_PROJ_SLUG -w release -b $CI_COMMIT_REF_NAME --stream

build-tags:
  image: cfmanteiga/alpine-bash-curl-jq
  stage: build
  only:
    - tags
  script:
    - chmod +x ./gitrise.sh
    - ./gitrise.sh -a $BITRISE_ACCESS_TOKEN -s $BITRISE_PROJ_SLUG -w release -t $CI_COMMIT_REF_NAME --stream

build-bottomsheet:
  image: cfmanteiga/alpine-bash-curl-jq
  stage: build
  only:
    - bottomsheet
  script:
    - chmod +x ./gitrise.sh
    - ./gitrise.sh -a $BITRISE_ACCESS_TOKEN -s $BITRISE_PROJ_SLUG -w release -b $CI_COMMIT_REF_NAME --stream