image: docker:20.10
services:
  - docker:20.10-dind

stages:
  - build

build-main:
  image: cfmanteiga/alpine-bash-curl-jq
  stage: build
  only:
    - main
  script:
    - chmod +x ./gitrise.sh
    - ./gitrise.sh -a $BITRISE_ACCESS_TOKEN -s $BITRISE_PROJ_SLUG -w release -b $CI_COMMIT_REF_NAME --stream

build-develop:
   image: cfmanteiga/alpine-bash-curl-jq
   stage: build
   only:
     - develop
   script:
     - chmod +x ./gitrise.sh
     - ./gitrise.sh -a $BITRISE_ACCESS_TOKEN -s $BITRISE_PROJ_SLUG -w release -b $CI_COMMIT_REF_NAME --stream