image: docker:20.10
services:
  - docker:20.10-dind

stages:
  - qa

quality:
  image: sonarsource/sonar-scanner-cli:4.6
  before_script: []
  stage: qa
  script:
    - sonar-scanner -Dsonar.login=$SONAR_TOKEN
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  only:
    - merge_requests
    - develop