image: docker:20.10
services:
  - docker:20.10-dind

stages:
  - qa
  - build

quality:
  image: sonarsource/sonar-scanner-cli:4.6
  before_script: []
  stage: qa
  script:
    - sonar-scanner -Dsonar.login=$SONAR_TOKEN
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  only:
    - merge_requests
    - develop

build-main:
  image: cfmanteiga/alpine-bash-curl-jq
  stage: build
  only:
    - main
  script:
    - chmod +x ./gitrise.sh
    - ./gitrise.sh -a $BITRISE_ACCESS_TOKEN -s $BITRISE_PROJ_SLUG -w release -b $CI_COMMIT_REF_NAME --stream

build-develop:
   image: cfmanteiga/alpine-bash-curl-jq
   stage: build
   only:
     - develop
   script:
     - chmod +x ./gitrise.sh
     - ./gitrise.sh -a $BITRISE_ACCESS_TOKEN -s $BITRISE_PROJ_SLUG -w release -b $CI_COMMIT_REF_NAME --stream